version: '3.2'

networks:
  md-network:
    driver: bridge
services:
  redis:
    container_name: redis
    image: redislabs/redismod:latest
    ports:
    - 6379:6379
    networks:
    - md-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8082:8081
    networks:
    - md-network
  redis-exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis:6379
    ports:
    - 9121:9121
    networks:
    - md-network

  rmqnamesrv:
    image: apacherocketmq/rocketmq
    container_name: rmqnamesrv
    ports:
    - 9876:9876
    volumes:
    - ./data/rocketmq/logs:/home/rocketmq/logs
    - ./data/rocketmq/store:/home/rocketmq/store
    command: sh mqnamesrv
    networks:
    - md-network

  broker:
    image: apache/rocketmq:5.1.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    restart: always
    privileged: true
    volumes:
      # 宿主机目录：容器目录
      - ./data/rocketmq/logs:/opt/logs
      - ./data/rocketmq/store:/opt/store
      - ./config/rocketmq/broker.conf:/etc/rocketmq/broker.conf
    depends_on:
      - 'rmqnamesrv'
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf"]
    networks:
    - md-network
  rmqconsole:
    image: styletang/rocketmq-console-ng:latest
    container_name: rocketmq-console
    ports:
    - 8076:8080
    depends_on:
    - rmqnamesrv
    environment:
    - JAVA_OPTS= -Dlogging.level.root=info  -Drocketmq.namesrv.addr=rmqnamesrv:9876
    - Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
    - md-network




