server:
  port: 8899
  id: 1

spring:
  redis:
    database: 0
    host: local.marding.cn
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
    address: redis://local.marding.cn:6379

websocket:
  enable: true
  port: 8878



jwt:
  accessToken:
    secret: marding

rocketmq:
  name-server: local.marding.cn:9876
  producer:
    group: im-server-group

local:
  cache:
    type: guava

distribute:
  cache:
    type: redis
  lock:
    type: redisson

redis:
  arrange:
    type: single # single or cluster
